import { NextResponse } from "next/server";
import { requireActiveMembership, requireCondominiumAccess } from "@/lib/auth";
import { toProdutoDto } from "@/lib/dtos/marketplace";
import { badRequest, createErrorResponse, forbidden, notFound, validationError } from "@/lib/http/errors";
import { buscarVinculoAtivoDoCondomino } from "@/lib/repositories/membros.repository";
import { buscarCategoria, criarProduto, listarProdutos } from "@/lib/repositories/produtos.repository";
import { getPagination, uuidSchema } from "@/lib/validations/common";
import { createProdutoSchema, productQuerySchema } from "@/lib/validations/produtos";
type Context = { params: Promise<{ condominioId: string }> };
async function id(context: Context) { const parsed = uuidSchema.safeParse((await context.params).condominioId); if (!parsed.success) throw validationError(parsed.error); return parsed.data; }
export async function GET(request: Request, context: Context) { try { const condominioId = await id(context); const auth = await requireCondominiumAccess(condominioId); const query = productQuerySchema.safeParse(Object.fromEntries(new URL(request.url).searchParams)); if (!query.success) throw validationError(query.error); if (query.data.mine && !auth.vinculoId) throw forbidden("E necessario possuir vinculo ativo para consultar produtos proprios."); const includeInactive = Boolean(query.data.includeInactive) && auth.role !== "member"; const pagination = getPagination(query.data); const [produtos, total] = await listarProdutos({ condominioId, vinculoId: auth.vinculoId, includeInactive, search: query.data.search, categoriaId: query.data.categoriaId, mine: query.data.mine, skip: pagination.skip, take: pagination.limit }); return NextResponse.json({ data: produtos.map(toProdutoDto), page: pagination.page, limit: pagination.limit, total, totalPages: Math.ceil(total / pagination.limit) }); } catch (error) { return createErrorResponse(error, "Erro ao buscar produtos."); } }
export async function POST(request: Request, context: Context) { try { const condominioId = await id(context); const auth = await requireActiveMembership(condominioId); const body = await request.json().catch(() => { throw badRequest("JSON invalido."); }); const parsed = createProdutoSchema.safeParse(body); if (!parsed.success) throw validationError(parsed.error); const vinculo = await buscarVinculoAtivoDoCondomino(condominioId, auth.user.condominoId!, parsed.data.vinculoId); if (!vinculo) throw forbidden("Vinculo de vendedor invalido."); if (!await buscarCategoria(parsed.data.categoriaId)) throw notFound("Categoria nao encontrada."); const produto = await criarProduto({ condominioId, vinculoId: vinculo.id, categoriaId: parsed.data.categoriaId, nome: parsed.data.nome, descricao: parsed.data.descricao, preco: parsed.data.preco, estoque: parsed.data.estoque }); return NextResponse.json({ data: toProdutoDto(produto) }, { status: 201 }); } catch (error) { return createErrorResponse(error, "Erro ao criar produto."); } }
