import { NextResponse } from "next/server";
import { requireCondominiumAccess, requireCondominiumAdmin } from "@/lib/auth";
import { toApartamentoDto } from "@/lib/dtos/marketplace";
import { badRequest, conflict, createErrorResponse, notFound, validationError } from "@/lib/http/errors";
import { atualizarApartamento, buscarApartamento, desativarApartamento } from "@/lib/repositories/apartamentos.repository";
import { updateApartamentoSchema } from "@/lib/validations/apartamentos";
import { uuidSchema } from "@/lib/validations/common";
type Context = { params: Promise<{ condominioId: string; apartamentoId: string }> };
async function ids(context: Context) { const params = await context.params; const c = uuidSchema.safeParse(params.condominioId); const a = uuidSchema.safeParse(params.apartamentoId); if (!c.success) throw validationError(c.error); if (!a.success) throw validationError(a.error); return { condominioId: c.data, apartamentoId: a.data }; }
export async function GET(_request: Request, context: Context) { try { const { condominioId, apartamentoId } = await ids(context); await requireCondominiumAccess(condominioId); const apartamento = await buscarApartamento(condominioId, apartamentoId); if (!apartamento) throw notFound(); return NextResponse.json({ data: toApartamentoDto(apartamento) }); } catch (error) { return createErrorResponse(error, "Erro ao buscar apartamento."); } }
export async function PATCH(request: Request, context: Context) { try { const { condominioId, apartamentoId } = await ids(context); await requireCondominiumAdmin(condominioId); if (!await buscarApartamento(condominioId, apartamentoId)) throw notFound(); const body = await request.json().catch(() => { throw badRequest("JSON invalido."); }); const result = updateApartamentoSchema.safeParse(body); if (!result.success) throw validationError(result.error); const apartamento = await atualizarApartamento(condominioId, apartamentoId, result.data); return NextResponse.json({ data: toApartamentoDto(apartamento) }); } catch (error) { return createErrorResponse(error, "Erro ao atualizar apartamento."); } }
export async function DELETE(_request: Request, context: Context) { try { const { condominioId, apartamentoId } = await ids(context); await requireCondominiumAdmin(condominioId); if (!await buscarApartamento(condominioId, apartamentoId)) throw notFound(); if (!await desativarApartamento(condominioId, apartamentoId)) throw conflict("Apartamento possui vinculos ativos."); return new Response(null, { status: 204 }); } catch (error) { return createErrorResponse(error, "Erro ao desativar apartamento."); } }
