import { NextResponse } from "next/server";
import { requireCondominiumAccess, requireCondominiumAdmin } from "@/lib/auth";
import { toMembroDto } from "@/lib/dtos/marketplace";
import { badRequest, conflict, createErrorResponse, notFound, validationError } from "@/lib/http/errors";
import { atualizarMembro, buscarMembro, buscarVinculoDoCondomino, desativarMembro } from "@/lib/repositories/membros.repository";
import { uuidSchema } from "@/lib/validations/common";
import { updateMembroSchema } from "@/lib/validations/membros";
type Context = { params: Promise<{ condominioId: string; vinculoId: string }> };
async function ids(context: Context) { const params = await context.params; const c = uuidSchema.safeParse(params.condominioId); const v = uuidSchema.safeParse(params.vinculoId); if (!c.success) throw validationError(c.error); if (!v.success) throw validationError(v.error); return { condominioId: c.data, vinculoId: v.data }; }
export async function GET(_request: Request, context: Context) { try { const { condominioId, vinculoId } = await ids(context); const auth = await requireCondominiumAccess(condominioId); const permitted = auth.role !== "member" || (auth.user.condominoId && await buscarVinculoDoCondomino(condominioId, auth.user.condominoId, vinculoId)); if (!permitted) throw notFound(); const membro = await buscarMembro(condominioId, vinculoId); if (!membro) throw notFound(); return NextResponse.json({ data: toMembroDto(membro) }); } catch (error) { return createErrorResponse(error, "Erro ao buscar membro."); } }
export async function PATCH(request: Request, context: Context) { try { const { condominioId, vinculoId } = await ids(context); await requireCondominiumAdmin(condominioId); if (!await buscarMembro(condominioId, vinculoId)) throw notFound(); const body = await request.json().catch(() => { throw badRequest("JSON invalido."); }); const parsed = updateMembroSchema.safeParse(body); if (!parsed.success) throw validationError(parsed.error); const membro = await atualizarMembro(condominioId, vinculoId, parsed.data); if (!membro) throw notFound("Apartamento nao encontrado no condominio."); return NextResponse.json({ data: toMembroDto(membro) }); } catch (error) { return createErrorResponse(error, "Erro ao atualizar vinculo."); } }
export async function DELETE(_request: Request, context: Context) { try { const { condominioId, vinculoId } = await ids(context); await requireCondominiumAdmin(condominioId); if (!await buscarMembro(condominioId, vinculoId)) throw notFound(); if (!await desativarMembro(condominioId, vinculoId)) throw conflict("Ha pedidos em andamento ligados a este vinculo."); return new Response(null, { status: 204 }); } catch (error) { return createErrorResponse(error, "Erro ao remover vinculo."); } }
