"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { useState } from "react";
import { z } from "zod";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
const password = z.string().min(8).regex(/[a-z]/).regex(/[A-Z]/).regex(/\d/).regex(/[^A-Za-z0-9]/);
export function AuthForm({ mode }: { mode: "login" | "register" }) { const router = useRouter(); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [email, setEmail] = useState(""); const [secret, setSecret] = useState(""); const [confirm, setConfirm] = useState(""); const register = mode === "register";
  async function submit(e: React.FormEvent) { e.preventDefault(); setMessage(""); const schema = register ? z.object({ email: z.email(), password, confirm: z.string() }).refine((v) => v.password === v.confirm, { message: "As senhas não coincidem." }) : z.object({ email: z.email(), password: z.string().min(1) }); const parsed = schema.safeParse({ email, password: secret, confirm }); if (!parsed.success) return setMessage(parsed.error.issues[0].message); setBusy(true); try { const result = await api<{ emailConfirmationRequired?: boolean }>(`/api/auth/${mode}`, { method: "POST", body: JSON.stringify({ email, password: secret }) }); if (register && result.emailConfirmationRequired) setMessage("Verifique seu email para continuar."); else router.replace("/"); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível continuar."); } finally { setBusy(false); } }
 return <Card className="w-full max-w-md"><CardHeader><CardTitle>{register ? "Crie sua conta" : "Bem-vindo de volta"}</CardTitle><CardDescription>{register ? "Use um email válido para se cadastrar." : "Entre na sua conta para acessar o condomínio."}</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label>Email</Label><Input value={email} onChange={(e) => setEmail(e.target.value)} type="email" autoComplete="email" required /></div><div className="space-y-2"><Label>Senha</Label><div className="relative"><Input value={secret} onChange={(e) => setSecret(e.target.value)} type={show ? "text" : "password"} autoComplete={register ? "new-password" : "current-password"} required /><button className="absolute right-3 top-2.5 text-muted-foreground" type="button" onClick={() => setShow(!show)}>{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div>{register && <><div className="space-y-2"><Label>Confirmar senha</Label><Input value={confirm} onChange={(e) => setConfirm(e.target.value)} type={show ? "text" : "password"} required /></div><p className="text-xs leading-5 text-muted-foreground">8+ caracteres, maiúscula, minúscula, número e caractere especial.</p></>}{message && <p className="rounded-lg bg-muted p-3 text-sm">{message}</p>}<Button className="w-full" type="submit" disabled={busy}>{busy && <Loader2 className="animate-spin" />} {register ? "Cadastrar" : "Entrar"}</Button></form><p className="mt-5 text-center text-sm text-muted-foreground">{register ? "Já possui conta?" : "Ainda não tem uma conta?"} <Link className="font-semibold text-primary" href={register ? "/login" : "/register"}>{register ? "Entrar" : "Cadastre-se"}</Link></p></CardContent></Card>; }
