import { NextResponse } from "next/server";
import { requireCondominiumAccess } from "@/lib/auth";
import { toProdutoDto } from "@/lib/dtos/marketplace";
import { badRequest, createErrorResponse, forbidden, notFound, validationError } from "@/lib/http/errors";
import { buscarVinculoAtivoDoCondomino } from "@/lib/repositories/membros.repository";
import { atualizarProduto, buscarCategoria, buscarProduto, desativarProduto } from "@/lib/repositories/produtos.repository";
import { uuidSchema } from "@/lib/validations/common";
import { updateProdutoSchema } from "@/lib/validations/produtos";
type Context = { params: Promise<{ condominioId: string; produtoId: string }> };
async function ids(context: Context) { const params = await context.params; const c = uuidSchema.safeParse(params.condominioId); const p = uuidSchema.safeParse(params.produtoId); if (!c.success) throw validationError(c.error); if (!p.success) throw validationError(p.error); return { condominioId: c.data, produtoId: p.data }; }
async function canManage(condominioId: string, produto: NonNullable<Awaited<ReturnType<typeof buscarProduto>>>, auth: Awaited<ReturnType<typeof requireCondominiumAccess>>) { if (auth.role !== "member") return true; return Boolean(auth.user.condominoId && await buscarVinculoAtivoDoCondomino(condominioId, auth.user.condominoId, produto.vendedor_vinculo_id)); }
export async function GET(_request: Request, context: Context) { try { const { condominioId, produtoId } = await ids(context); const auth = await requireCondominiumAccess(condominioId); const produto = await buscarProduto(condominioId, produtoId, auth.role !== "member"); if (!produto) throw notFound(); return NextResponse.json({ data: toProdutoDto(produto) }); } catch (error) { return createErrorResponse(error, "Erro ao buscar produto."); } }
export async function PATCH(request: Request, context: Context) { try { const { condominioId, produtoId } = await ids(context); const auth = await requireCondominiumAccess(condominioId); const produto = await buscarProduto(condominioId, produtoId, true); if (!produto) throw notFound(); if (!await canManage(condominioId, produto, auth)) throw forbidden("Voce nao pode alterar este produto."); const body = await request.json().catch(() => { throw badRequest("JSON invalido."); }); const parsed = updateProdutoSchema.safeParse(body); if (!parsed.success) throw validationError(parsed.error); if (parsed.data.categoriaId && !await buscarCategoria(parsed.data.categoriaId)) throw notFound("Categoria nao encontrada."); const updated = await atualizarProduto(condominioId, produtoId, parsed.data); return NextResponse.json({ data: toProdutoDto(updated) }); } catch (error) { return createErrorResponse(error, "Erro ao atualizar produto."); } }
export async function DELETE(_request: Request, context: Context) { try { const { condominioId, produtoId } = await ids(context); const auth = await requireCondominiumAccess(condominioId); const produto = await buscarProduto(condominioId, produtoId, true); if (!produto) throw notFound(); if (!await canManage(condominioId, produto, auth)) throw forbidden("Voce nao pode desativar este produto."); await desativarProduto(condominioId, produtoId); return new Response(null, { status: 204 }); } catch (error) { return createErrorResponse(error, "Erro ao desativar produto."); } }
